name: i3config
description: Read i3 config files

version: 1.1.1
repository: https://github.com/kingwill101/dart_i3config

environment:
  sdk: ">=3.4.1 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
